### PR TITLE
added another item

### PR DESCRIPTION
**Pull request by shoppingcuestas**
Can you please review it? Thanks

### CODE REVIEW

**Comment by caleb-sophia-madrid** [comment]
##  Staging deploy 
 https://caleb-sophia-madrid-dev.herokuapp.com/

**Comment by caleb-sophia-madrid** [comment]
##  Staging deploy 
 https://caleb-sophia-madrid-dev.herokuapp.com/

**Comment by shoppingcuestas** [comment]
Whenever you want, if that is ok with you

**Comment by caleb-sophia-madrid** [comment]
##  Staging deploy 
 https://caleb-sophia-madrid-dev.herokuapp.com/

**Pull request merged**
