### PR TITLE
Butterfly

### PR DESCRIPTION
**Pull request by lauragonzalvez**

### CODE REVIEW

**Comment by caleb-sophia-madrid** [comment]
##  Staging deploy 
 https://caleb-sophia-madrid-dev.herokuapp.com/

**Comment by shoppingcuestas** [comment]
Very nice job! Thanks

**Comment by caleb-sophia-madrid** [comment]
##  Staging deploy 
 https://caleb-sophia-madrid-dev.herokuapp.com/

**Comment by caleb-sophia-madrid** [comment]
##  Staging deploy 
 https://caleb-sophia-madrid-dev.herokuapp.com/

**Pull request merged**
