### PR TITLE
teddy_bear

### PR DESCRIPTION
**Pull request by shoppingcuestas**
For review:
I have some other versions, just in case  you don´t like this one

### CODE REVIEW

**Comment by josemimartin** [comment]
@samuelfernandez Are we overwriting existing assets, or creating new assets and adding them to the game?

**Comment by caleb-sophia-madrid** [comment]
##  Staging deploy 
 https://caleb-sophia-madrid-dev.herokuapp.com/

**Comment by shoppingcuestas** [comment]
@samuelfernandez  Im overwriting them, shouldn´t I?

**Comment by samuelfernandez** [comment]
@shoppingcuestas @josemimartin Yep, no problem with overwriting. This way we can see them live, I'll come later to cleanup related code and renaming

**Comment by caleb-sophia-madrid** [comment]
##  Staging deploy 
 https://caleb-sophia-madrid-dev.herokuapp.com/

**Comment by caleb-sophia-madrid** [comment]
##  Staging deploy 
 https://caleb-sophia-madrid-dev.herokuapp.com/

**Pull request merged**
